apiVersion: v1
kind: Service
metadata:
  name: sp-frontend
  namespace: my-app-xlab
spec:
  clusterIP: None  # This makes it a headless service
  selector:
    app: sp-frontend
  ports:
    - port: 5000
      targetPort: 5000
