version: "3.9"
name: nsf-service-provider-employer-demo
services:

  employer_frontend:
    build: "./progressive/manager/employer front end"
    container_name: employer-frontend
    ports:
      - 8003:5000
    depends_on:
      - db
    networks:
      - network

  db:
    image: postgres
    container_name: employer-db
    ports:
      - 5435:5432
    networks:
      - network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword

  web:
    build: "./progressive/manager/dashboard server/django_backend/"
    container_name: employer-backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - "./progressive/manager/dashboard server/django_backend/:/app"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - network
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_HOST=db
      - DB_PORT=5432

  controller:
    build:
      context: "./nsf-service-provider-controller"
      dockerfile: ./demo/Dockerfile
    container_name: service-provider-controller
    ports:
      - 8081:8081
    depends_on:
      - web
      - acapy_agent
    networks:
      - network
    environment:
      AGENT_URL: http://acapy_agent:8021
      BACKEND_API_HOST: web
      BACKEND_API_PORT: 8000
  
  acapy_agent:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.6-indy-1.16.0-0.8.1
    container_name: service-provider-acapy-agent
    ports:
      - 8021:8021
      - 8020:8020
    depends_on:
     - acapy_wallet_db
    networks:
      - network
    command: start --arg-file "//service-provider-agent-args.yaml" --wallet-storage-config '{"url":"acapy_wallet_db:5432","max_connections":5, "wallet_scheme":"DatabasePerWallet"}' --wallet-storage-creds '{"account":"postgres","password":"postgres","admin_account":"postgres","admin_password":"postgres"}'
  
  acapy_wallet_db:
    image: postgres:14.1-alpine
    container_name: service-provider-acapy-postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5434:5432
    networks:
      - network
    volumes: 
      - postgres_data_acapy_wallet:/var/lib/postgresql/data

networks:
  network:
    driver: bridge

volumes:
  postgres_data_acapy_wallet:
    driver: local

