apiVersion: v1
kind: Service
metadata:
  name: user-acapy-agent
  namespace: my-app-xlab
spec:
  clusterIP: None  # Headless service
  selector:
    app: user-acapy-agent
  ports:
  - name: admin  # Name for the admin port
    port: 9031
    targetPort: 9031
  - name: inbound  # Name for the inbound transport port
    port: 9030
    targetPort: 9030
