version: "3.9"
name: nsf-user-employee-demo
services:

  employee_frontend:
    build: "./progressive/employee/frontend"
    container_name: employee-frontend
    ports:
      - 3001:3000 # Using port 3001 instead of 3000 so that frontend team can run frontend locally as well.
    depends_on:
      - dataplug
    networks:
      - network
    environment:
      REACT_APP_USER_AGENT_CONTROLLER_BASE_URL: "http://localhost:8080"
      REACT_APP_SERVICE_PROVIDER_AGENT_BASE_URL: "http://localhost:8021"
      REACT_APP_DP_BASE_URL: "http://localhost:8001"
      REACT_APP_BASE_URL: "http://localhost:3001"
      REACT_APP_PORT: 3001

  dataplug:
    build: "./progressive/employee/dataplug/"
    container_name: data-plug
    ports:
      - 8001:8001
    depends_on:
      - controller
      - dataplug_db
    networks:
      - network
    env_file: "./progressive/employee/dataplug/.env"
    # ^ NOTE: env_file automatically passes env vars to the container (don't need to specify them here in the compose file).
    environment:
      USER_AGENT_CONTROLLER_BASE_URL: http://controller:8080
      BASE_URL: "http://host.docker.internal:8001" # Can probably replace w service ref.
      MONGODB_URI: mongodb://dataplug_db:27017
      PORT: 8001

  dataplug_db:
    image: mongo:latest
    container_name: dataplug-mongo-db
    ports:
      - 27018:27017
    networks:
      - network
    volumes:
      - dataplug_mongodb_data:/data/db

  model:
    build: "./progressive/model"
    container_name: model
    ports:
      - 5001:5001
    networks:
      - network
  
  controller:
    build:
      context: "./nsf-user-controller"
    container_name: user-controller
    ports:
      - 8080:8080
    depends_on:
      - controller_db
      - acapy_agent
    networks:
      - network
    environment:
      AGENT_URL: http://acapy_agent:8031
      MONGO_DB_URI: mongodb://controller_db:27017

  controller_db:
    image: mongo:latest
    container_name: user-controller-mongo-db
    ports:
      - 27017:27017
    networks:
      - network
    volumes:
      - controller_mongodb_data:/data/db
  
  acapy_agent:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.6-indy-1.16.0-0.8.1
    container_name: user-acapy-agent
    ports:
      - 8031:8031
      - 8030:8030
    depends_on:
     - acapy_wallet_db
    networks:
      - network
    # TODO comment arg meanings:
    # --endpoint is used to communicate to other agents, so it must be resolvable outside of the docker compose network.
    command: >
      start
      --inbound-transport http 0.0.0.0 8030
      --outbound-transport http
      --endpoint 'http://host.docker.internal:8030'
      --label 'user.agent'
      --admin-insecure-mode
      --admin 0.0.0.0 8031
      --no-ledger
      --auto-provision
      --wallet-type askar
      --wallet-name user-wallet
      --wallet-key wallet-password
      --wallet-storage-type postgres_storage
      --wallet-storage-config '{"url":"acapy_wallet_db:5432","max_connections":5, "wallet_scheme":"DatabasePerWallet"}'
      --wallet-storage-creds '{"account":"postgres","password":"postgres","admin_account":"postgres","admin_password":"postgres"}'

  acapy_wallet_db:
    image: postgres:14.1-alpine
    container_name: user-acapy-postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    networks:
      - network
    volumes: 
      - postgres_data:/var/lib/postgresql/data

networks:
  network:
    driver: bridge

volumes:
  dataplug_mongodb_data:
  controller_mongodb_data:
  postgres_data:
    driver: local
