version: "3.9"
name: nsf-user-employee-demo
services:

  # TODO employee frontend

  dataplug:
    build: "./progressive/employee/dataplug/"
    container_name: data-plug
    ports:
      - 8001:8001
    depends_on:
      - controller
      - dataplug_db
    networks:
      - network
    environment:
      USER_AGENT_CONTROLLER_BASE_URL: http://controller:8031
      SERVICE_PROVIDER_AGENT_BASE_URL: ${SERVICE_PROVIDER_AGENT_BASE_URL} # TODO remove this? I don't think user-side should be communicating directly with service provider (outside of invitations).
      BASE_URL: "http://host.docker.internal:8001" # Can probably replace w service ref.
      MONGODB_URI: mongodb://host.docker.internal:27018 # mongodb://dataplug_db:27018 fails
      METRIPORT_API_KEY: ${METRIPORT_API_KEY}
      METRIPORT_API_URL: ${METRIPORT_API_URL}
      CREATE_INVITATION_BODY: ${CREATE_INVITATION_BODY}
      SECRET: ${SECRET}
      PORT: 8001

  dataplug_db:
    image: mongo:latest
    container_name: dataplug-mongo-db
    ports:
      - 27018:27017
    networks:
      - network
    volumes:
      - dataplug_mongodb_data:/data/db
  
  controller:
    build:
      context: "./nsf-user-controller"
      dockerfile: ./demo/Dockerfile
    container_name: user-controller
    ports:
      - 8080:8080
    depends_on:
      - controller_db
      - acapy_agent
    networks:
      - network
    environment:
      AGENT_URL: http://acapy_agent:8031
      MONGO_DB_URI: mongodb://controller_db:27017

  controller_db:
    image: mongo:latest
    container_name: user-controller-mongo-db
    ports:
      - 27017:27017
    networks:
      - network
    volumes:
      - controller_mongodb_data:/data/db
  
  acapy_agent:
    build:
      context: "./nsf-acapy"
      dockerfile: ./nsf-demo/nsf-demo.Dockerfile
    container_name: user-acapy-agent
    ports:
      - 8031:8031
      - 8030:8030
    depends_on:
     - acapy_wallet_db
    networks:
      - network
    command: start --arg-file "//user-agent-args.yaml" --wallet-storage-config '{"url":"acapy_wallet_db:5432","max_connections":5, "wallet_scheme":"DatabasePerWallet"}' --wallet-storage-creds '{"account":"postgres","password":"postgres","admin_account":"postgres","admin_password":"postgres"}'
  
  acapy_wallet_db:
    image: postgres:14.1-alpine
    container_name: user-acapy-postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    networks:
      - network
    volumes: 
      - postgres_data:/var/lib/postgresql/data

networks:
  network:
    driver: bridge

volumes:
  dataplug_mongodb_data:
  controller_mongodb_data:
  postgres_data:
    driver: local
