apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db-pvc
  namespace: my-app-xlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Specify the storage size you need