apiVersion: v1
kind: Service
metadata:
  name: user-controller-mongo-db
  namespace: my-app-xlab
spec:
  clusterIP: None  # Headless service
  selector:
    app: user-controller-mongo-db
  ports:
  - port: 27017
    targetPort: 27017