apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-frontend
  namespace: my-app-xlab
spec:
  serviceName: "user-frontend"
  replicas: 2
  selector:
    matchLabels:
      app: user-frontend
  template:
    metadata:
      labels:
        app: user-frontend
    spec:
      imagePullSecrets:
      - name: my-registry-secret1
      containers:
      - name: user-frontend
        image: nsf-user-employee-demo-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_USER_CONTROLLER_BASE_URL
          value: "http://user-controller-$(HOSTNAME).my-app-xlab:9080"  # Ensure each user-frontend talks to corresponding controller
        - name: AGENT_URL
          value: "http://user-acapy-agent-$(HOSTNAME).my-app-xlab:9031"
        - name: PORT
          value: "3000"
