apiVersion: v1
kind: Service
metadata:
  name: user-controller
  namespace: my-app-xlab
spec:
  clusterIP: None  # Headless service
  selector:
    app: user-controller
  ports:
  - port: 9080
    targetPort: 9080

