apiVersion: v1
kind: Service
metadata:
  name: user-frontend
  namespace: my-app-xlab
spec:
  clusterIP: None  # Headless service
  selector:
    app: user-frontend
  ports:
  - port: 3000
    targetPort: 3000
