version: "3.9"
name: issuer-test
services:
  acapy_agent:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.12.0rc2
    container_name: issuer-acapy-agent
    ports:
      - 9071:9071
      - 9070:9070
    depends_on:
     - acapy_wallet_db
    networks:
      - network
    # TODO comment arg meanings:
    # --endpoint is used to communicate to other agents, so it must be resolvable outside of the docker compose network.
    # keep teh --webhook-url hostname to the host's localhost instead of a service reference, because that way we can swap out a locally running controller.
    #--auto-accept-invites --auto-accept-requests --auto-ping-connection --auto-respond-messages --auto-respond-credential-proposal --auto-respond-credential-offer --auto-respond-credential-request --auto-verify-presentation --auto-store-credential
    command: >
      start
      --seed 0923456ERFDZSXCVTYUO9986OREDFBBB
      --debug-credentials
      --log-level 'debug'
      --inbound-transport http 0.0.0.0 9070
      --outbound-transport http
      --endpoint 'http://host.docker.internal:9070'
      --webhook-url 'http://host.docker.internal:9077/webhook'
      --label 'user.agent'
      --admin-insecure-mode
      --admin 0.0.0.0 9071
      --genesis-url 'http://host.docker.internal:9000/genesis'
      --log-level 'debug'
      --auto-accept-invites
      --auto-provision
      --wallet-type askar
      --wallet-name user-wallet
      --wallet-key wallet-password
      --wallet-storage-type postgres_storage
      --wallet-storage-config '{"url":"acapy_wallet_db:5432","max_connections":5, "wallet_scheme":"DatabasePerWallet"}'
      --wallet-storage-creds '{"account":"postgres","password":"postgres","admin_account":"postgres","admin_password":"postgres"}'

  acapy_wallet_db:
    image: postgres:14.1-alpine
    container_name: issuer-acapy-postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5437:5432
    networks:
      - network
    volumes: 
      - postgres_data:/var/lib/postgresql/data

networks:
  network:
    driver: bridge

volumes:
  controller_mongodb_data:
  postgres_data:
    driver: local
